name: Publish to GitHub Packages

on:
  workflow_call:
    inputs:
      generated_version:
        required: true
        type: string
      repo_owner:
        required: true
        type: string
      repo_name:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 from Azul Zulu
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Debug generated_version
        run: |
          echo "Generated version is: ${{ inputs.generated_version }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: target
          merge-multiple: true

      - name: Configure Maven settings with custom path
        uses: s4u/maven-settings-action@v3.1.0
        with:
          settings-path: settings.xml
          servers: >
            [
              {
                "id": "github",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]

      - name: Set dynamic version
        run: |
          mvn versions:set -DnewVersion=${{ inputs.generated_version }}

      - name: Rename custom jar
        run: |
          mv target/built-${{ inputs.generated_version }}.jar target/mcrul-ipc-${{ inputs.generated_version }}.jar

      - name: Deploy using mvn deploy
        run: |
          mvn deploy -Drevision=${{ inputs.generated_version }} 
      


